[package]
name = "krissh-wtf/axis"
description = "An agnostic, simple and versatile input library for ECS"
version = "0.2.21"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
homepage = "https://neond00m.github.io/Axis/"

exclude = ["**"]
include = [
	"default.project.json",
    "src",
	"src/*",
	"wally.toml",
	"README.md",
	"LICENSE",
]